import { useState } from 'react'

// Páginas legais públicas (produto-01 da mega spec): institucionais, não
// autenticadas, não branded por tenant — são sobre o app "Agente IA" da
// Rangel Tech perante a Meta, não sobre um cliente específico. Publicadas
// agora (piloto) e marcadas para revisão jurídica formal antes de cliente
// pagante real (decisão do dono, 17/08/2026).

type Lang = 'pt' | 'en'
type Page = 'privacidade' | 'termos' | 'exclusao'

const CONTACT_EMAIL = 'privacidade@rangeltech.net'

function Toggle({ lang, onChange }: { lang: Lang; onChange: (l: Lang) => void }) {
  return (
    <div className="mb-8 flex justify-end gap-2 text-sm">
      <button
        onClick={() => onChange('pt')}
        className={`rounded-full px-3 py-1 ${lang === 'pt' ? 'bg-[var(--brand)] text-white' : 'border border-[var(--border)] text-[var(--text-muted)]'}`}
      >
        Português
      </button>
      <button
        onClick={() => onChange('en')}
        className={`rounded-full px-3 py-1 ${lang === 'en' ? 'bg-[var(--brand)] text-white' : 'border border-[var(--border)] text-[var(--text-muted)]'}`}
      >
        English
      </button>
    </div>
  )
}

function Shell({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mx-auto min-h-screen max-w-3xl px-6 py-12 text-[var(--text)]">
      <a href="/" className="text-sm text-[var(--text-muted)] hover:underline">
        ← Agente IA — Rangel Tech
      </a>
      <h1 className="mt-4 mb-2 text-3xl font-semibold">{title}</h1>
      <p className="mb-8 text-sm text-[var(--text-faint)]">Rangel Tech · Última atualização: 17/08/2026</p>
      <div className="space-y-6 leading-7 text-[var(--text-muted)]">{children}</div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-2 text-lg font-medium text-[var(--text)]">{title}</h2>
      <div className="space-y-2">{children}</div>
    </section>
  )
}

function Privacidade({ lang }: { lang: Lang }) {
  if (lang === 'en') {
    return (
      <Shell title="Privacy Policy">
        <p>
          This Privacy Policy describes how <strong>Rangel Tech</strong> ("we", "us") collects, uses and
          protects data through the app <strong>"Agente IA"</strong>, which connects to Instagram, Facebook
          Messenger and WhatsApp on behalf of businesses ("clients") that use our customer service
          platform.
        </p>
        <Section title="Data we receive">
          <p>
            When a client connects a channel (Instagram, Messenger or WhatsApp) to our platform, we
            receive: message content exchanged between the client's end customers and the client's
            business account, sender contact identifiers provided by the channel (e.g. Instagram/WhatsApp
            user ID, phone number when applicable), and message metadata (timestamps, attachment
            references).
          </p>
        </Section>
        <Section title="Connected channels">
          <p>Instagram (Business Login), Facebook Messenger, WhatsApp Cloud API (Embedded Signup), and TikTok (when enabled for a client).</p>
        </Section>
        <Section title="How messages are used">
          <p>
            Messages are routed to the client's support inbox (Chatwoot) and, when the client enables it,
            to an AI agent that drafts or sends automatic replies. Messages are never used for advertising,
            sold to third parties, or used to train models outside the client's own configured AI
            provider.
          </p>
        </Section>
        <Section title="Use of AI">
          <p>
            Replies can be generated by an AI agent configured by the client. When a conversation is
            handled automatically, this is disclosed to the end user; the client can enable human handoff
            at any time, and the end user can request to speak with a human agent.
          </p>
        </Section>
        <Section title="Storage">
          <p>
            Data is stored on infrastructure operated by Rangel Tech (self-hosted database and object
            storage), isolated per client (multi-tenant isolation — one client can never access another
            client's data or credentials).
          </p>
        </Section>
        <Section title="Sharing">
          <p>
            We do not sell or share end-customer data with third parties, except: (a) the messaging
            provider itself (Meta or TikTok, depending on the connected channel), as required to
            deliver/receive the message; (b) the AI provider
            configured by the client (e.g. an LLM API) strictly to generate a reply, under that provider's
            own data-processing terms; (c) when required by law.
          </p>
        </Section>
        <Section title="Security">
          <p>
            Channel credentials (access tokens) are encrypted at rest per client. Access to the platform
            requires authentication; each client's data is isolated from every other client's.
          </p>
        </Section>
        <Section title="Retention">
          <p>
            Conversation data is retained while the client's account is active, plus a reasonable period
            for support/audit purposes, unless a shorter period is requested (see Data Deletion).
          </p>
        </Section>
        <Section title="Deletion">
          <p>
            End users and clients may request deletion — see our{' '}
            <a className="underline" href="/exclusao-de-dados">
              Data Deletion
            </a>{' '}
            page.
          </p>
        </Section>
        <Section title="Revoking channel access">
          <p>
            A client can disconnect any Meta channel at any time from their account settings, or by
            revoking the app's access directly in their Meta/Instagram/Facebook account settings. Once
            revoked, we stop receiving new messages from that channel immediately.
          </p>
        </Section>
        <Section title="Contact">
          <p>
            Questions about this policy: <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          </p>
        </Section>
      </Shell>
    )
  }
  return (
    <Shell title="Política de Privacidade">
      <p>
        Esta Política de Privacidade descreve como a <strong>Rangel Tech</strong> ("nós") coleta, usa e
        protege dados através do app <strong>"Agente IA"</strong>, que conecta Instagram, Facebook
        Messenger e WhatsApp em nome de empresas ("clientes") que usam nossa plataforma de atendimento.
      </p>
      <Section title="Quais dados recebemos">
        <p>
          Quando um cliente conecta um canal (Instagram, Messenger ou WhatsApp) à nossa plataforma,
          recebemos: o conteúdo das mensagens trocadas entre o cliente final e a conta comercial do
          nosso cliente, identificadores de contato fornecidos pelo próprio canal (ex.: ID de usuário do
          Instagram/WhatsApp, número de telefone quando aplicável) e metadados da mensagem (horário,
          referência de anexos).
        </p>
      </Section>
      <Section title="Canais integrados">
        <p>Instagram (Business Login), Facebook Messenger, WhatsApp Cloud API (Embedded Signup) e TikTok (quando habilitado para um cliente).</p>
      </Section>
      <Section title="Uso das mensagens">
        <p>
          As mensagens são roteadas para a caixa de atendimento do cliente (Chatwoot) e, quando o cliente
          habilita, para um agente de IA que gera ou envia respostas automáticas. Mensagens nunca são
          usadas para publicidade, vendidas a terceiros, nem usadas para treinar modelos fora do provedor
          de IA que o próprio cliente configurou.
        </p>
      </Section>
      <Section title="Uso de Inteligência Artificial">
        <p>
          Respostas podem ser geradas por um agente de IA configurado pelo cliente. Quando uma conversa é
          atendida automaticamente, isso é informado ao usuário final; o cliente pode habilitar
          transferência para atendimento humano a qualquer momento, e o usuário final pode pedir para
          falar com uma pessoa.
        </p>
      </Section>
      <Section title="Armazenamento">
        <p>
          Os dados ficam armazenados em infraestrutura operada pela Rangel Tech (banco de dados e storage
          de objetos próprios), isolados por cliente (isolamento multi-tenant — um cliente nunca acessa
          dado ou credencial de outro).
        </p>
      </Section>
      <Section title="Compartilhamento">
        <p>
          Não vendemos nem compartilhamos dados do cliente final com terceiros, exceto: (a) o próprio
          provedor de mensageria (Meta ou TikTok, dependendo do canal conectado), na medida necessária
          para entregar/receber a mensagem; (b) o
          provedor de IA configurado pelo cliente (ex.: uma API de LLM), estritamente para gerar a
          resposta, sob os próprios termos de tratamento de dados desse provedor; (c) quando exigido por
          lei.
        </p>
      </Section>
      <Section title="Segurança">
        <p>
          Credenciais de canal (tokens de acesso) são criptografadas em repouso, por cliente. O acesso à
          plataforma exige autenticação; os dados de cada cliente ficam isolados dos demais.
        </p>
      </Section>
      <Section title="Retenção">
        <p>
          Dados de conversa ficam retidos enquanto a conta do cliente estiver ativa, mais um período
          razoável para suporte/auditoria, salvo pedido de prazo menor (ver Exclusão de Dados).
        </p>
      </Section>
      <Section title="Exclusão">
        <p>
          Usuários finais e clientes podem solicitar exclusão — ver nossa página de{' '}
          <a className="underline" href="/exclusao-de-dados">
            Exclusão de Dados
          </a>
          .
        </p>
      </Section>
      <Section title="Revogação de autorização do canal">
        <p>
          O cliente pode desconectar qualquer canal Meta a qualquer momento nas configurações da própria
          conta, ou revogando o acesso do app diretamente nas configurações da conta Meta/Instagram/
          Facebook. Uma vez revogado, paramos de receber novas mensagens desse canal imediatamente.
        </p>
      </Section>
      <Section title="Contato">
        <p>
          Dúvidas sobre esta política: <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
        </p>
      </Section>
    </Shell>
  )
}

function Termos({ lang }: { lang: Lang }) {
  if (lang === 'en') {
    return (
      <Shell title="Terms of Use">
        <Section title="Service">
          <p>
            "Agente IA" is a customer-service platform operated by Rangel Tech, allowing businesses to
            connect messaging channels (Instagram, Messenger, WhatsApp) and use an AI agent and/or a human
            team to reply to their end customers.
          </p>
        </Section>
        <Section title="Client responsibilities">
          <p>
            Clients are responsible for the accounts/pages they connect, for the content of automated
            replies they configure, and for complying with the messaging platform's own policies (no
            spam, no unauthorized bulk messaging, respecting messaging windows).
          </p>
        </Section>
        <Section title="Automated responses disclosure">
          <p>
            When a conversation is handled by an AI agent, this must be disclosed to the end user per the
            messaging platform's policies and this platform's defaults.
          </p>
        </Section>
        <Section title="Changes">
          <p>These terms may be updated; material changes will be communicated to active clients.</p>
        </Section>
        <Section title="Contact">
          <p>
            <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          </p>
        </Section>
      </Shell>
    )
  }
  return (
    <Shell title="Termos de Uso">
      <Section title="O serviço">
        <p>
          "Agente IA" é uma plataforma de atendimento operada pela Rangel Tech, que permite a empresas
          conectar canais de mensageria (Instagram, Messenger, WhatsApp) e usar um agente de IA e/ou uma
          equipe humana para responder seus clientes finais.
        </p>
      </Section>
      <Section title="Responsabilidades do cliente">
        <p>
          O cliente é responsável pelas contas/páginas que conecta, pelo conteúdo das respostas
          automáticas que configura, e por cumprir as próprias políticas da plataforma de mensageria (sem
          spam, sem disparo em massa não autorizado, respeitando as janelas de mensagem).
        </p>
      </Section>
      <Section title="Divulgação de atendimento automatizado">
        <p>
          Quando uma conversa é atendida por um agente de IA, isso deve ser informado ao usuário final,
          conforme as políticas da plataforma de mensageria e o padrão desta plataforma.
        </p>
      </Section>
      <Section title="Alterações">
        <p>Estes termos podem ser atualizados; mudanças relevantes serão comunicadas a clientes ativos.</p>
      </Section>
      <Section title="Contato">
        <p>
          <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
        </p>
      </Section>
    </Shell>
  )
}

function Exclusao({ lang }: { lang: Lang }) {
  if (lang === 'en') {
    return (
      <Shell title="Data Deletion">
        <Section title="How to request deletion">
          <p>
            End users or clients may request deletion of their data by emailing{' '}
            <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> from the
            address associated with the account, or via the messaging channel itself by requesting
            deletion, in which case the client's support team will forward the request to us.
          </p>
        </Section>
        <Section title="What gets deleted">
          <p>
            Conversation history, contact data and any AI-extracted memory tied to the requester's
            identifier on the connected channel. We will confirm completion by email within a reasonable
            timeframe.
          </p>
        </Section>
        <Section title="Revoking the app instead">
          <p>
            To immediately stop new data collection without waiting for a deletion request to be
            processed, disconnect/revoke the app's access in your Instagram/Facebook/WhatsApp account
            settings at any time.
          </p>
        </Section>
      </Shell>
    )
  }
  return (
    <Shell title="Exclusão de Dados">
      <Section title="Como pedir exclusão">
        <p>
          Usuários finais ou clientes podem pedir a exclusão dos seus dados enviando e-mail para{' '}
          <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> a partir do
          endereço associado à conta, ou pelo próprio canal de mensageria pedindo a exclusão — nesse caso
          a equipe de atendimento do cliente encaminha o pedido para nós.
        </p>
      </Section>
      <Section title="O que é excluído">
        <p>
          Histórico de conversa, dado de contato e qualquer memória extraída pela IA vinculada ao
          identificador de quem pediu, no canal conectado. Confirmamos a conclusão por e-mail em prazo
          razoável.
        </p>
      </Section>
      <Section title="Revogar o app em vez de esperar">
        <p>
          Para parar imediatamente a coleta de novos dados sem esperar o processamento do pedido de
          exclusão, desconecte/revogue o acesso do app nas configurações da sua conta Instagram/Facebook/
          WhatsApp a qualquer momento.
        </p>
      </Section>
    </Shell>
  )
}

export default function Legal({ page }: { page: Page }) {
  const [lang, setLang] = useState<Lang>('pt')
  return (
    <div className="min-h-screen bg-[var(--bg)]">
      <div className="mx-auto max-w-3xl px-6 pt-6">
        <Toggle lang={lang} onChange={setLang} />
      </div>
      {page === 'privacidade' && <Privacidade lang={lang} />}
      {page === 'termos' && <Termos lang={lang} />}
      {page === 'exclusao' && <Exclusao lang={lang} />}
    </div>
  )
}
